-- Initial approved knowledge seed for the Regal Master "Pokec" AI colleague.
--
-- Safety model:
-- - Only public.ai_* tables are touched.
-- - No orders, Ads, Meta, Upgates, Matrix or other business data is changed.
-- - Values are idempotent via unique slugs/source keys.

insert into public.ai_business_contexts
  (slug, title, body, topic, market, confidence, evidence, status, created_by, updated_at)
values
  (
    'revenue-aov-shipping-definition',
    'Revenue, AOV and shipping definition',
    'For Regal Master marketing economics, revenue means product revenue without VAT and without shipping. AOV uses the same product revenue basis. Shipping and cash-on-delivery revenue is tracked separately and must not enter PNO or product AOV.',
    'definitions',
    null,
    'confirmed',
    '[{"source":"operating_manual","field":"business definitions"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'margin-definition',
    'Gross profit and margin definition',
    'Gross profit is product selling price without VAT minus product buy price without VAT. Gross profit percentage is gross profit divided by product selling price without VAT. Orders with missing buy prices must be disclosed as incomplete.',
    'margin',
    null,
    'confirmed',
    '[{"source":"operating_manual","field":"margin formula"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'excluded-order-statuses',
    'Excluded business statuses',
    'Orders with STORNO or failed payment status such as Platba selhala must not be counted as real business orders for revenue, AOV, margin or marketing economics.',
    'definitions',
    null,
    'confirmed',
    '[{"source":"orders_dashboard","field":"excluded statuses"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'may-14-2026-pricing-and-bundles',
    'May 14 2026 pricing and bundles change',
    'On 2026-05-14 Regal Master significantly changed product prices and disabled the old automatic bundle discount logic. Any AOV, margin, bundle or campaign-mix analysis around this date must compare before and after periods explicitly.',
    'pricing',
    null,
    'confirmed',
    '[{"source":"business discussion","date":"2026-05-19"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'aov-product-mix-landing-pages',
    'AOV drop working hypothesis',
    'A recurring hypothesis is that AOV can drop when traffic is sent to cheap shelving products, categories sorted from cheapest first, or a homepage that highlights cheap products. This is a hypothesis, not a conclusion: the agent must verify product mix, landing pages, campaign mix and B2B/B2C signal.',
    'aov',
    null,
    'medium',
    '[{"source":"business discussion","date":"2026-05-21"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'bundle-products-need-separate-analysis',
    'Bundles need separate analysis',
    'Bundle and multi-pack products can affect both AOV and gross margin. The agent must identify bundle SKUs, show daily quantity, SKU breakdown, revenue and gross profit percentage, and must not assume all bundles are one dimension without evidence.',
    'bundles',
    null,
    'confirmed',
    '[{"source":"business discussion","date":"2026-05-22"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'landing-page-visual-guardrail',
    'Landing page visual guardrail',
    'The agent may analyze Ads landing_page and expanded_landing_page data. It must not claim what a page visually shows, how products are sorted, or what the hero emphasizes unless it has screenshot/browser evidence or a stored page scrape.',
    'landing_pages',
    null,
    'confirmed',
    '[{"source":"eval","id":"landing_page_visual_guardrail"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'ads-meta-read-only',
    'Ads and Meta are read-only',
    'Google Ads and Meta Ads integrations for Pokec are read-only. The agent may inspect spend, campaigns, landing pages and diagnostics, but must never change campaigns, budgets, bids, audiences, creatives or settings.',
    'ads',
    null,
    'confirmed',
    '[{"source":"safety policy","field":"ads read only"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'competition-needs-fresh-scrape',
    'Competition claims need fresh Matrix evidence',
    'Competitor claims must include last scraped or observed timestamp. Without fresh Matrix evidence, the agent may only propose competition as a hypothesis and must not claim that a competitor changed price, stock or assortment.',
    'competition',
    null,
    'confirmed',
    '[{"source":"operating_manual","field":"competition guardrail"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'three-month-priority-clear-warehouse',
    'Three month priority: maximize turnover and clear warehouse',
    'For the next three months Regal Master prioritizes revenue and stock rotation over margin optimization. The business expects roughly 11 containers and around 25 000 shelving units around late June and early July 2026, so the short-term objective is to create warehouse space and move volume even if margin quality is temporarily weaker.',
    'business_goals',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"3 month goal"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'twelve-month-targets-2026',
    'Twelve month target profile for 2026',
    'The year-end target is to reach 12 million CZK revenue without VAT, maintain HV1 above 60 percent and HV2 above 35 percent, while scaling across CZ, SK, HU and RO and staying open to Austria and Poland expansion if it helps growth.',
    'business_goals',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"12 month goal"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'pno-alarm-thresholds',
    'PNO alarm thresholds',
    'PNO above 30 percent is a major alarm during the current growth phase. After a market reaches more stable scale, PNO above 25 percent is a problem. Reference stability ceilings are roughly 6 million CZK in Czechia, 2 million CZK in Slovakia, 5 million CZK in Hungary and 4 million CZK in Romania, all spoken about on revenue including shipping and VAT in owner shorthand, so Pokec must restate metric definitions carefully when comparing against dashboard figures.',
    'ads',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"PNO thresholds"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'healthy-aov-thresholds',
    'Healthy AOV thresholds',
    'Healthy AOV is 2 000 CZK plus VAT and shipping or better. 2 200 CZK plus VAT and shipping is considered very good. Below 2 000 CZK is a business problem and a drop below 1 500 CZK plus VAT is clearly a poor order quality zone unless there is a strong strategic reason.',
    'aov',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"AOV heuristics"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'good-vs-bad-order-quality',
    'Good versus bad order quality',
    'A very good order is above 5 000 CZK plus VAT and shipping. A poor order is below 1 500 CZK plus VAT, especially if free shipping or other subsidy means Regal Master carries logistics cost. Pokec should use this framing when evaluating campaign quality and product mix, while still disclosing the exact product-revenue definition used in the dashboard.',
    'order_quality',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"good bad order"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'b2b-priority-signal',
    'B2B customers are strategically preferable',
    'Shelving is bought by both consumers and companies, but company customers are preferred because they usually drive higher AOV. Pokec should treat B2B mix deterioration as an important warning and should look for ways to identify when traffic quality shifts away from firm buyers.',
    'b2b',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"B2B priority"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'top-sellers-low-margin-180x90',
    'Top sellers 180x90x40 and 180x90x30',
    'The top-selling size families are 1800x900x400 and 1800x900x300. They are also highly competitive and generally lower-margin than many larger shelving variants. Pokec should assume these sizes can be traffic magnets and revenue drivers while still being dangerous for margin and AOV quality if they dominate too much.',
    'products',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"top sellers"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'missing-stock-large-heights',
    'Larger height products are supply constrained',
    'Products with 2000 mm and 2200 mm heights have recently been understocked, even though they are more expensive and usually have attractive margin. Pokec should treat missing stock as a possible hidden driver of AOV and mix changes before concluding that demand shifted naturally.',
    'products',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"stock constraints"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'product-family-taxonomy',
    'Core product family taxonomy',
    'Regal Master product families should be read at least through boltless, rivet, robust and professional shelves. These families differ in quality, load capacity and visual design. Incoming assortment also includes full metal shelving and double layer variants, so Pokec should not flatten every product into one generic shelf family when making business recommendations.',
    'products',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"product families"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'bundle-strategy-high-margin',
    'Bundles are strategically valuable when margin is high',
    'Bundles are desirable because they lift AOV. Ideal bundles are built on shelf families with gross margin above 60 percent. Pokec should therefore evaluate bundles not only by units sold, but by their ability to improve AOV without sacrificing overall gross profit quality.',
    'bundles',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"bundle strategy"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'four-markets-are-similar-until-data-proves-otherwise',
    'CZ, SK, HU and RO are similar until evidence says otherwise',
    'The owner view is that CZ, SK, HU and RO are broadly similar markets in customer need. Pokec should not invent strong country stereotypes without evidence. If conversion, AOV, margin or B2B mix differs, it should show the actual diagnostic signal and treat country-specific interpretation as data-led rather than assumption-led.',
    'markets',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"market similarity"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'same-core-assortment-across-all-four-shops',
    'All four shops should carry the same core assortment',
    'The four storefronts should sell the same core products. Intentional differences may exist in price strategy, but assortment gaps are usually a sign of product outage, sync error or availability issue rather than a country-specific assortment strategy. Pokec should therefore treat missing products on one market as a possible operational problem before turning it into a merchandising conclusion.',
    'markets',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-23","field":"same assortment across shops"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'storefront-assortment-parity-guardrail',
    'Storefront assortment gaps are an operational alarm',
    'When Pokec compares storefronts, it should assume the same core assortment should be available across CZ, SK, HU and RO. A visible product gap on one storefront is first an outage, synchronization or availability alarm, not a smart local merchandising choice.',
    'storefront',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-23","field":"same assortment across shops"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'free-shipping-threshold-adjustments',
    'Free shipping thresholds are changing by market',
    'On or around 2026-05-21 Czechia moved free shipping threshold up to 2 000 CZK, and Hungary and Romania may need similar changes because logistics are being subsidized too heavily on small orders. Pokec should treat shipping threshold changes as a first-class explanatory variable for order count, AOV and shipping revenue shifts.',
    'shipping',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"free shipping changes"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'lowest-price-guarantee-matters',
    'Lowest price guarantee matters commercially',
    'Regal Master uses a lowest price guarantee: if a customer finds the same shelf cheaper elsewhere, Regal Master matches the price. Pokec should remember that aggressive price positioning is not only a campaign issue but also a commercial promise that can support conversion while squeezing margin.',
    'pricing',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"lowest price guarantee"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'temporary-growth-over-margin-tradeoff',
    'Short term tradeoff favors turnover over margin',
    'Until the incoming container wave is absorbed, Pokec should evaluate ideas through a temporary growth-first lens: more revenue, faster stock rotation and warehouse space creation can be the right decision even when margin quality is weaker than the long-term target. It must still show the margin cost explicitly and distinguish temporary strategy from steady-state health.',
    'business_goals',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"growth over margin tradeoff"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'low-value-orders-are-a-structural-problem',
    'Very low value orders are a structural business problem',
    'A large number of orders under 1 000 CZK is structurally bad for the business. Pokec should treat clusters of tiny orders as a warning signal and check whether they are tied to subsidized shipping, cheap landing pages, consumer-heavy traffic or low-value SKU concentration.',
    'order_quality',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"many small orders problem"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'storefront-homepages-emphasize-price-stock-speed',
    'Storefront homepages emphasize price, stock and speed',
    'Across the country storefronts the visible pattern is strongly commercial: bestseller modules, strong sale framing, in-stock messaging, fast dispatch promises and lowest price guarantee language. Pokec should treat this as a real storefront pressure toward conversion and volume, not just a campaign artifact.',
    'storefront',
    null,
    'confirmed',
    '[{"source":"public storefront walkthrough","date":"2026-05-23","sites":["vyprodej-regalu.cz","vypredaj-regalov.sk","polc-kiarusitas.hu"]}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'storefront-product-pages-push-multipacks',
    'Product pages visibly push multi-pack buying',
    'Product detail pages visibly promote quantity bundles such as 3, 5, 10 and 20 pieces, and in some cases individual pricing from 30 pieces upward. Pokec should treat this as a built-in AOV lever and should connect bundle performance not only to SKU economics but also to storefront merchandising.',
    'storefront',
    null,
    'confirmed',
    '[{"source":"public storefront walkthrough","date":"2026-05-23","sites":["vyprodej-regalu.cz","vypredaj-regalov.sk","polc-kiarusitas.hu"]}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'storefront-categories-frame-use-cases-and-surface-finish',
    'Categories frame use cases and surface finish',
    'The storefront navigation and category copy repeatedly frame shelves by use case such as home, archive and warehouse, and by surface finish such as galvanized versus painted. Pokec should therefore read category traffic not just as generic list traffic but as intent traffic with merchandising meaning.',
    'storefront',
    null,
    'confirmed',
    '[{"source":"public storefront walkthrough","date":"2026-05-23","sites":["vyprodej-regalu.cz","vypredaj-regalov.sk","polc-kiarusitas.hu"]}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'dimension-finish-packsize-are-merchandising-signals',
    'Dimensions, finish and pack size are merchandising signals',
    'SKU names carry business meaning beyond the raw code. Width, depth, height, finish such as galvanized versus painted, color variants and pack size like 3 or 5 pieces should be read as merchandising signals that influence conversion, AOV and margin quality. Pokec should aggregate these dimensions when looking for mix shifts instead of staying only at single-SKU level.',
    'products',
    null,
    'confirmed',
    '[{"source":"owner_input","date":"2026-05-22","field":"products as families and dimensions"},{"source":"public storefront walkthrough","date":"2026-05-23"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'premium-families-can-sell-even-with-low-stock',
    'Premium and larger families can sell despite low stock',
    'Screenshots from product statistics suggest that larger and professional families continue to sell even when stock is visibly low, which means low observed sales can understate true demand. Pokec should treat low-stock premium families as potentially demand-constrained, not automatically weak products.',
    'products',
    null,
    'medium',
    '[{"source":"owner_input_screenshots","date":"2026-05-22","field":"product sales and stock screenshots"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'multipacks-are-not-only-for-cheap-skus',
    'Multipacks matter across cheap and premium families',
    'Multi-pack variants appear both on traffic-driver shelves and on larger or more premium families. Pokec should not assume bundles only belong to cheap entry products; it must compare whether bundles amplify low-value traffic or help push higher-value assortments.',
    'bundles',
    null,
    'medium',
    '[{"source":"owner_input_screenshots","date":"2026-05-22","field":"product sales and stock screenshots"},{"source":"public storefront walkthrough","date":"2026-05-23"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'google-ads-message-match-and-landing-page-relevance',
    'Google Ads requires strong message match and landing page relevance',
    'Google Ads best-practice guidance emphasizes that ads, keywords and landing pages should align closely and that specific call-to-action language improves conversion chances. Pokec should therefore treat weak message match and generic landing pages as high-priority suspects when traffic is expensive but order quality is poor.',
    'ads',
    null,
    'confirmed',
    '[{"source":"Google Ads Help","date":"2026-05-23","url":"https://support.google.com/google-ads/answer/6238826/optimising-your-ad-and-landing-page?hl=en-GB"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'google-ads-value-based-bidding-needs-real-values',
    'Value-based bidding needs trustworthy transaction values',
    'Google states that maximize conversion value and value-based bidding depend on conversion tracking with transaction-specific values. Pokec should prefer real revenue and margin-aware diagnostics and should treat weak value mapping as a major limit before endorsing value-based optimization ideas.',
    'ads',
    null,
    'confirmed',
    '[{"source":"Google Ads Help","date":"2026-05-23","url":"https://support.google.com/google-ads/answer/7684216?hl=en-419&ref_topic=16431842"},{"source":"Google value-based bidding guide","date":"2026-05-23","url":"https://services.google.com/fh/files/emails/value_based_bidding_best_practice_guide.pdf"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'google-retail-pmax-feed-quality-matters',
    'Retail Performance Max quality depends on feed quality',
    'Google retail best practices for Performance Max emphasize strong Merchant Center feed quality and product data enrichment. Pokec should therefore treat weak product feed structure, poor titles or missing merchandising signals as possible causes of bad shopping performance, not just bidding or budget issues.',
    'ads',
    null,
    'confirmed',
    '[{"source":"Google retailer best practices","date":"2026-05-23","url":"https://business.google.com/us/accelerate/resources/articles/retailer-best-practices-for-ai-powered-performance-max-campaigns/"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'meta-sales-objective-needs-pixel-or-capi-and-sales-signal',
    'Meta sales optimization needs clean purchase signals',
    'Meta official guidance for Sales campaigns depends on pixel or Conversions API quality and purchase-oriented optimization signals. Pokec should therefore distrust Meta performance conclusions when measurement setup is incomplete and should distinguish media problems from tracking problems.',
    'meta',
    null,
    'confirmed',
    '[{"source":"Meta for Business","date":"2026-05-23","url":"https://www.facebook.com/business/ads/ad-objectives/sales"},{"source":"Meta Business Help Center","date":"2026-05-23","url":"https://www.facebook.com/business/help/AboutConversionsAPI"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'meta-creative-diversification-and-placement-breadth',
    'Meta benefits from creative diversification and placement breadth',
    'Meta official guidance emphasizes diversified creative, high-quality visuals and broad placement coverage rather than overly narrow manual assumptions. Pokec should therefore check whether Meta weakness may come from stale creative mix or overly constrained delivery before blaming audience quality alone.',
    'meta',
    null,
    'confirmed',
    '[{"source":"Meta for Business","date":"2026-05-23","url":"https://www.facebook.com/business/ads/ad-creative"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'baymard-homepage-category-ux-matters-for-range-comprehension',
    'Homepage and category UX affect range comprehension',
    'Baymard research shows that homepage and category navigation strongly affect whether shoppers understand the breadth of a catalog and can find relevant products. Pokec should therefore treat homepage and category merchandising as a conversion and AOV lever, not just a cosmetic site issue.',
    'cro',
    null,
    'confirmed',
    '[{"source":"Baymard Institute","date":"2026-05-23","url":"https://baymard.com/research/homepage-and-category-usability"},{"source":"Baymard Institute","date":"2026-05-23","url":"https://baymard.com/learn/ecommerce-ux-best-practices"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'baymard-shipping-thresholds-and-checkout-friction-matter',
    'Shipping visibility and checkout friction matter',
    'Baymard checkout research highlights shipping cost visibility and checkout friction as major conversion factors. Pokec should therefore connect free-shipping thresholds, shipping subsidy policy and cart experience to both conversion rate and order quality, instead of treating shipping only as a logistics line item.',
    'cro',
    null,
    'confirmed',
    '[{"source":"Baymard Institute","date":"2026-05-23","url":"https://baymard.com/research/checkout-usability"},{"source":"Baymard Institute","date":"2026-05-23","url":"https://baymard.com/learn/checkout-flow-ux-optimization"}]'::jsonb,
    'active',
    'system_seed',
    now()
  ),
  (
    'import-logistics-read-only-doctrine',
    'Import logistics doctrine',
    'Pokec answers import logistics questions from live Supabase import logistics views and Upgates stock/purchase-price data. It is read-only: it must not change import statuses, upload documents or repair product matches. Čína 0526 is the source sheet for business order Čína 13. Forecasts must disclose +20 percent month-over-month growth and business-clean sales velocity excluding STORNO and failed payments.',
    'import_logistics',
    null,
    'confirmed',
    '[{"source":"supabase/import_logistics.sql","date":"2026-05-27","field":"import logistics doctrine"}]'::jsonb,
    'active',
    'system_seed',
    now()
  )
on conflict (slug) do update set
  title = excluded.title,
  body = excluded.body,
  topic = excluded.topic,
  market = excluded.market,
  confidence = excluded.confidence,
  evidence = excluded.evidence,
  status = excluded.status,
  created_by = excluded.created_by,
  updated_at = now();

insert into public.ai_data_sources
  (source_key, label, system_name, tables_or_views, freshness_requirement, can_answer, known_limits, allowed_operations, mutation_allowed, status, updated_at)
values
  (
    'upgates_orders',
    'Upgates orders',
    'Upgates -> Supabase',
    '["orders","order_business_daily_summary"]'::jsonb,
    'Current-day order sync must be fresh before diagnosing today.',
    '["orders by day and market","product mix","AOV without VAT/shipping","shipping revenue","B2B/B2C signal","margin from buy prices"]'::jsonb,
    '["missing buy_price lowers margin confidence","STORNO and failed payments must be excluded"]'::jsonb,
    '["select"]'::jsonb,
    false,
    'active',
    now()
  ),
  (
    'google_ads',
    'Google Ads',
    'Google Ads API -> Supabase',
    '["ad_metrics_daily","ad_campaigns","ad_landing_pages_daily","marketing_business_daily_total"]'::jsonb,
    'Campaign spend should be refreshed within roughly 45 minutes; deeper detail is daily.',
    '["spend by country","PNO","real ROAS","campaigns","search terms","shopping products","landing pages","hour/device/geo diagnostics"]'::jsonb,
    '["platform conversion value can differ from real Upgates revenue","read-only only"]'::jsonb,
    '["select"]'::jsonb,
    false,
    'active',
    now()
  ),
  (
    'meta_ads',
    'Meta Ads',
    'Meta Marketing API -> Supabase',
    '["ad_metrics_daily","ad_campaigns","marketing_business_provider_daily_summary"]'::jsonb,
    'Meta sync freshness must be checked before comparing Meta against Google.',
    '["spend by country","campaigns","ad sets","ads","placements","audiences","Meta vs Google comparison"]'::jsonb,
    '["Meta may be unavailable until access and sync are configured","read-only only"]'::jsonb,
    '["select"]'::jsonb,
    false,
    'active',
    now()
  ),
  (
    'small_ga',
    'Small GA / tracker',
    'RM Smartlook analytics tracker -> CORE Supabase',
    '["sl_*","small_ga_*"]'::jsonb,
    'Tracker and ingestion must be verified for the selected site and period.',
    '["sessions","landing pages","source/medium/campaign","cart events","purchase events","paid vs organic behavior"]'::jsonb,
    '["if tracker is not live, the agent must not claim landing page behavior","visual claims need screenshot or scrape"]'::jsonb,
    '["select"]'::jsonb,
    false,
    'active',
    now()
  ),
  (
    'matrix_competition',
    'Matrix competition',
    'matrix.regalmaster.cz',
    '["competitor_*","ai_competitor_observations"]'::jsonb,
    'Every competitor claim must carry last scraped/observed timestamp.',
    '["competitor prices","availability","new products","assortment changes","country comparison"]'::jsonb,
    '["without fresh scrape, competition is only a hypothesis"]'::jsonb,
    '["select"]'::jsonb,
    false,
    'active',
    now()
  ),
  (
    'import_logistics',
    'Import logistics',
    'Supabase import logistics + Upgates stock/purchase prices + business-clean orders',
    '["import_orders","import_order_lines","import_order_shipments","import_order_documents","import_order_costs","import_product_matches","upgates_product_purchase_prices_current","upgates_product_stock_current","import_logistics_order_overview","import_logistics_sku_risk","import_logistics_landed_cost_changes","import_logistics_match_gaps","import_logistics_document_coverage"]'::jsonb,
    'Pokec must read live Supabase import logistics views and disclose coverage for prices, documents, freight/KN invoices, matches and unknown quantities.',
    '["orders currently on the way","ETA Čína 9/10/11/12/13","current stock plus inbound","stockout risk","Upgates NC vs import cost vs landed cost","match review","document coverage"]'::jsonb,
    '["Čína 0526 is business order Čína 13","Čína 13 may have unknown quantities until supplemental documents are imported","landed cost is incomplete without prices and KN/freight invoices","stockout claims require stock/inbound/velocity coverage"]'::jsonb,
    '["select"]'::jsonb,
    false,
    'active',
    now()
  )
on conflict (source_key) do update set
  label = excluded.label,
  system_name = excluded.system_name,
  tables_or_views = excluded.tables_or_views,
  freshness_requirement = excluded.freshness_requirement,
  can_answer = excluded.can_answer,
  known_limits = excluded.known_limits,
  allowed_operations = excluded.allowed_operations,
  mutation_allowed = excluded.mutation_allowed,
  status = excluded.status,
  updated_at = now();

insert into public.ai_examples
  (slug, title, trigger_patterns, expected_behavior, required_playbooks, good_answer, bad_answer, must_include, must_not_claim_without_evidence, status, updated_at)
values
  (
    'aov-drop-hu-example',
    'AOV drop in HU',
    '["pokles AOV","HU","prumerna hodnota objednavky","levne produkty"]'::jsonb,
    '["compare current and previous periods","show product mix changes","check bundle impact","check Ads landing pages","disclose missing small GA/visual evidence"]'::jsonb,
    '["aov_drop","landing_page_problem"]'::jsonb,
    'A good answer separates facts from hypotheses: product mix changed, AOV moved by X, top SKU share moved by Y, landing page data is/is not available, and the next step is to verify page/category experience if visual evidence is missing.',
    'A bad answer says PPC definitely sends bad customers or HP definitely shows cheap products without landing page and visual evidence.',
    '["product mix","period comparison","landing pages","missing data","confidence"]'::jsonb,
    '["definite PPC blame","visual landing page claim without screenshot","new number outside tool output"]'::jsonb,
    'active',
    now()
  ),
  (
    'margin-drop-today-example',
    'Today margin drop',
    '["dnes","marze","zisk","nakupka"]'::jsonb,
    '["show exact vs missing orders","show low-margin SKU","check bundle share","explain sample size","do not blame Ads without linkage"]'::jsonb,
    '["margin_drop"]'::jsonb,
    'A good answer starts with sample size and exact order count, then shows low-margin SKU and missing buy prices, and only then discusses possible drivers.',
    'A bad answer says margin calculation is broken or Ads caused it without SKU and cost evidence.',
    '["exact orders","missing buy prices","low-margin SKU","bundle impact","sample size"]'::jsonb,
    '["calculation is wrong without audit","Ads caused margin drop"]'::jsonb,
    'active',
    now()
  ),
  (
    'memory-candidate-example',
    'Memory candidate only',
    '["uloz do pameti","zapamatuj si","priste s tim pocitej"]'::jsonb,
    '["save only as ai_memory_candidates","mark pending","include evidence","do not call it approved memory"]'::jsonb,
    '["missing_data"]'::jsonb,
    'A good answer says the learning was saved as a pending candidate for human review and business data was unchanged.',
    'A bad answer says the AI permanently updated approved memory or changed business data.',
    '["ai_memory_candidates","pending","human review","business data unchanged"]'::jsonb,
    '["approved truth","changed orders","changed Ads"]'::jsonb,
    'active',
    now()
  ),
  (
    'growth-first-tradeoff-example',
    'Growth first but transparent about margin cost',
    '["obrat za kazdou cenu","udelat misto na skladu","ted neresit marzi","11 kontejneru"]'::jsonb,
    '["explicitly state temporary goal tradeoff","show revenue benefit and margin cost separately","do not normalize high PNO as healthy forever","anchor recommendation in 3 month vs 12 month goals"]'::jsonb,
    '["high_pno","product_mix_change","country_change"]'::jsonb,
    'A good answer says the current phase can justify weaker margin quality if turnover and stock rotation improve, but it still quantifies the tradeoff and flags when the business is drifting too far from long-term HV1/HV2 targets.',
    'A bad answer says margin no longer matters or treats every growth period as permission to ignore economics.',
    '["short term goal","long term goal","tradeoff","evidence","guardrail"]'::jsonb,
    '["margin does not matter","ignore PNO permanently","growth explains everything"]'::jsonb,
    'active',
    now()
  ),
  (
    'storefront-walkthrough-example',
    'Storefront walkthrough must separate visible page reality from data-only hypotheses',
    '["jak vypada shop","co tlaci homepage","balicky na produktu","kategorie dle vyuziti"]'::jsonb,
    '["distinguish visible storefront evidence from analytics inference","use screenshot or public page evidence for visual claims","connect merchandising patterns to AOV and order quality carefully"]'::jsonb,
    '["landing_page_problem","product_mix_change","bundle_diagnostics"]'::jsonb,
    'A good answer says the storefront visibly emphasizes low price, stock and quick shipping, or that a PDP visibly offers 3/5/10/20 piece bundles, and then explains what that could mean for AOV while still separating hypothesis from measured business impact.',
    'A bad answer claims a storefront design pattern without page evidence or uses one visual observation as proof of business causality.',
    '["visual evidence","hypothesis separation","merchandising meaning","next step"]'::jsonb,
    '["visual claim without page evidence","storefront caused AOV drop with no data"]'::jsonb,
    'active',
    now()
  ),
  (
    'assortment-intelligence-example',
    'Assortment intelligence must roll SKU detail into families and ladders',
    '["co se prodava", "jake rodiny tlaci obrat", "kterym produktum chybi sklad", "jake produkty jsou premium"]'::jsonb,
    '["group SKU into dimension, finish, family and pack-size ladders","separate traffic drivers from margin drivers","check stock constraints before judging weak demand","show where bundle variants change the story"]'::jsonb,
    '["product_mix_change","margin_drop","bundle_diagnostics","country_change"]'::jsonb,
    'A good answer says which families drive volume, which likely carry better margin, where stock shortages may be hiding demand and how pack-size variants change order quality. It uses SKU detail as evidence but explains the assortment in a merchant-friendly way.',
    'A bad answer just lists top SKU rows or declares a family bad without checking whether it is understocked, premium or bundled differently.',
    '["family grouping","dimension or finish ladder","stock constraint caveat","bundle role","merchant interpretation"]'::jsonb,
    '["top SKU list with no interpretation","weak demand claim without stock context"]'::jsonb,
    'active',
    now()
  ),
  (
    'trusted-external-best-practices-example',
    'External best practices must come from trusted primary sources',
    '["best practice v ads","co rika google","co rika meta","cro best practice"]'::jsonb,
    '["prefer official platform docs and serious UX research","separate platform best practice from Regal-specific evidence","do not import guru folklore as fact","show when an external best practice still needs local validation"]'::jsonb,
    '["high_pno","landing_page_problem","campaign_mix_change","missing_data"]'::jsonb,
    'A good answer says Google or Meta official guidance suggests a certain optimization principle, but then checks whether Regal Master data supports it before making a recommendation.',
    'A bad answer cites vague marketer wisdom or treats a generic platform recommendation as if it already proved the root cause in Regal Master.',
    '["source quality","local validation","platform guidance","uncertainty"]'::jsonb,
    '["guru quote as fact","generic best practice equals proven root cause"]'::jsonb,
    'active',
    now()
  )
on conflict (slug) do update set
  title = excluded.title,
  trigger_patterns = excluded.trigger_patterns,
  expected_behavior = excluded.expected_behavior,
  required_playbooks = excluded.required_playbooks,
  good_answer = excluded.good_answer,
  bad_answer = excluded.bad_answer,
  must_include = excluded.must_include,
  must_not_claim_without_evidence = excluded.must_not_claim_without_evidence,
  status = excluded.status,
  updated_at = now();

insert into public.ai_open_questions
  (title, body, topic, market, priority, status, needed_data, updated_at)
values
  (
    'Connect small GA landing pages to Pokec answers',
    'Pokec should use small GA paid and organic landing page sessions when diagnosing AOV, landing page and traffic-quality problems.',
    'small_ga',
    null,
    'high',
    'open',
    '["small GA live readiness","session to source/medium/campaign mapping","landing page classification"]'::jsonb,
    now()
  ),
  (
    'Verify Matrix freshness before competitor explanations',
    'Competition explanations need fresh Matrix scrape timestamps and product/category matching before they can be stated as facts.',
    'competition',
    null,
    'medium',
    'open',
    '["latest Matrix scrape","competitor SKU/category mapping","market-specific comparison"]'::jsonb,
    now()
  ),
  (
    'Map B2B-quality signals by market and traffic source',
    'Pokec should learn how to detect when traffic quality shifts away from firm buyers, because B2B orders tend to have stronger AOV and business value than small consumer orders.',
    'b2b',
    null,
    'high',
    'open',
    '["B2B classification logic by market","order-size distribution by channel","campaign to B2B proxy mapping"]'::jsonb,
    now()
  ),
  (
    'Quantify lost AOV from missing 2000 mm and 2200 mm stock',
    'Large and high-margin shelf heights appear supply constrained. Pokec should estimate how much AOV and gross profit opportunity is being lost because 2000 mm and 2200 mm families are out of stock or understocked.',
    'products',
    null,
    'high',
    'open',
    '["historic stock availability by SKU","sales velocity by height family","margin by SKU family","back-in-stock timing"]'::jsonb,
    now()
  ),
  (
    'Build data-led market profiles instead of stereotypes',
    'CZ, SK, HU and RO should be profiled from actual conversion, AOV, margin, shipping and B2B mix data rather than assumed stereotypes. Pokec should keep refreshing those profiles as evidence accumulates.',
    'markets',
    null,
    'medium',
    'open',
    '["market-level AOV/margin/B2B baselines","shipping subsidy by market","campaign mix by market","small GA landing page mix by market"]'::jsonb,
    now()
  ),
  (
    'Refresh public storefront walkthroughs periodically',
    'Storefront copy, categories, bundle modules and shipping banners can change. Pokec should periodically refresh public walkthrough memory so that visible shop claims stay current and do not fossilize from one point in time.',
    'storefront',
    null,
    'medium',
    'open',
    '["fresh homepage snapshots by market","fresh category snapshots","fresh PDP snapshots for top sellers and high-margin families"]'::jsonb,
    now()
  ),
  (
    'Build assortment ladders by family, finish and pack size',
    'Pokec should learn to aggregate SKU-level data into merchant-friendly assortment ladders: family type, dimensions, surface finish, color and multi-pack size. This is needed to explain whether growth comes from healthy breadth or from overconcentration in cheap entry shelves.',
    'products',
    null,
    'high',
    'open',
    '["SKU parser for dimensions and pack size","family mapping table","margin by family ladder","stock and sales by ladder"]'::jsonb,
    now()
  ),
  (
    'Identify which premium families deserve more traffic when back in stock',
    'Some larger, taller or professional families may deserve stronger merchandising and paid support when stock returns, because they can improve AOV and gross profit more than traffic-driver entry shelves.',
    'pricing',
    null,
    'medium',
    'open',
    '["family-level margin ranking","historic demand while in stock","landing page and campaign mapping for premium families"]'::jsonb,
    now()
  ),
  (
    'Curate trusted external CRO and paid-media doctrine for Pokec',
    'Pokec should maintain a vetted external doctrine layer sourced from primary platform docs and high-quality ecommerce UX research. Google Ads, Meta and Baymard should outrank agency folklore unless Regal Master evidence proves otherwise.',
    'cro',
    null,
    'medium',
    'open',
    '["official Google Ads guidance mapping","official Meta guidance mapping","Baymard-derived UX checklist","local validation examples"]'::jsonb,
    now()
  )
on conflict do nothing;
